#!/usr/bin/env bash
#
# nodetalking

# BASH MODES
set -u
set -o pipefail

# CONSTANTS
readonly HOME_DIR="$( cd "$( dirname $0 )" ; pwd )"
readonly INCLUDES_DIR="${HOME_DIR}/includes"

# INCLUDES
source "${INCLUDES_DIR}/bp.sh"
source "${INCLUDES_DIR}/nodetalking_vars.sh"
source "${INCLUDES_DIR}/nodetalking_functions.sh"

# MAIN
main() {
  
  # Sets up files, etc if this is our first run
  nt::setup

  # Checks if script is already locked
  nt::check_lock

  # Locks the script
  nt::lock

  # Checks that the host file isn't empty
  nt::check_hosts_file

  # Checks defined hosts
  nt::check_hosts

  # Unlocks script
  nt::unlock
}

main $@
